import Head from  'next/head'
import Header from './header'
import dynamic from 'next/dynamic'
import { useEffect, useState } from 'react'
import useMusixStore from '@/shared/store'
import { useRouter } from 'next/router'
import LoadingSpinner from '../loading'

export default function MobileLayout({ children }: Props) {
  const [isHydrated, setIsHydrated] = useState(false);
  const user = useMusixStore(state => state.user);
  const router = useRouter();

  useEffect(() => {
    setIsHydrated(true);
  }, []);
  
  // wait for hydration
  if (!isHydrated) {
    return <LoadingSpinner />
  }

  // if user is not logged in, redirect to login page
  if (!user) {
    router.push(`/`);
    return <LoadingSpinner />
  }
  
  return (
    <>
      <Head>
        <title>Musix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <div className="flex flex-col h-full">
        <Header />
        <DynamicToaster />
        <main className="grow py-6 px-4">
          {children}
        </main>
      </div>
    </>
  )
}

// ------------------------------ //
// dynamic imports

const DynamicToaster = dynamic(
  () => import("./toaster"), { ssr: false }
);

// ------------------------------ //
// types

type Props = {
  children: React.ReactNode;
}