import Head from  'next/head'
import Header from './header'
import dynamic from 'next/dynamic'

export default function MobileLayout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Musix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <div className="flex flex-col h-full">
        <Header />
        <DynamicToaster />
        <main className="grow py-6 px-4">
          {children}
        </main>
      </div>
    </>
  )
}

// ------------------------------ //
// dynamic imports

const DynamicToaster = dynamic(
  () => import("./toaster"), { ssr: false }
);

// ------------------------------ //
// types

type Props = {
  children: React.ReactNode;
}